n1 = int(input("Enter no 1: "))
n2 = int(input("Enter no 2: "))
n3 = int(input("Enter no 3: "))
n4 = int(input("Enter no 4: "))
n5 = int(input("Enter no 5: "))
n6 = int(input("Enter no 6: "))
n7 = int(input("Enter no 7: "))
n8 = int(input("Enter no 8: "))

s = set()

s.add(n1)
s.add(n2)
s.add(n3)
s.add(n4)
s.add(n5)
s.add(n6)
s.add(n7)
s.add(n8)

print("The uniqe digits are : ",s)
